### ISSUE TITLE
Request for Comment: RetroPGF dashboard

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/optimism-project-ideas#3]
Hello Optimism Team!

I put together a dashboard on [Notion](https://chain-television-f40.notion.site/43fdbefb120941ee9c9bb8ff290be860?v=bbd36980f8314f349ad7c19e0eb52b1b) with a quick blurb on RPGF, links to relevant blog posts, and the funding break down from round 1. I was wondering if this was the type of thing y'all were looking for and I was hoping for some feedback on how to improve it!

I'm open to programming something up too, but I thought throwing up a quick MVP might be good for now. Thanks!

**Comment by zainbacchus** [comment]
@sbvegan 

This is incredible work! Love how you're using the direct sources to support data quality and making extensible by including which RetroPGF version the grant is from. 

Are you open to chatting more about potential next steps?

**Comment by sbvegan** [comment]
Hey @zainbacchus thanks! Yeah I'm open to that. We can either chat here or you can send me an email with what you're thinking.

**Comment by zainbacchus** [comment]
Just emailed you :)
